services:
  postgres:
    image: postgres:17
    container_name: local_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shortcut-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_backend
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
      - shortcut-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pg_data:

networks:
  shortcut-network:
    driver: bridge